import { ensureTab } from "../lib/sheets";
import {
  VENDOR_TAB_NAME, VENDOR_COLUMNS,
  CHART_OF_ACCOUNT_TAB_NAME, CHART_OF_ACCOUNT_COLUMNS,
  PRODUCT_TAB_NAME, PRODUCT_COLUMNS,
  COMPANY_BANK_ACCOUNT_TAB_NAME, COMPANY_BANK_ACCOUNT_COLUMNS,
  USER_TAB_NAME, USER_COLUMNS,
  PURCHASE_ORDER_TAB_NAME, PURCHASE_ORDER_COLUMNS,
  PO_ITEM_TAB_NAME, PO_ITEM_COLUMNS,
  GOODS_RECEIPT_TAB_NAME, GOODS_RECEIPT_COLUMNS,
  GOODS_RECEIPT_ITEM_TAB_NAME, GOODS_RECEIPT_ITEM_COLUMNS,
  ACCOUNTS_PAYABLE_TAB_NAME, ACCOUNTS_PAYABLE_COLUMNS,
  PAYMENT_PREP_TAB_NAME, PAYMENT_PREP_COLUMNS,
  PAYMENT_PREP_ITEM_TAB_NAME, PAYMENT_PREP_ITEM_COLUMNS,
  PAYMENT_TAB_NAME, PAYMENT_COLUMNS,
} from "../lib/sheets-tables";

process.loadEnvFile(".env.local");

async function main() {
  for (const [tabName, columns] of [
    [VENDOR_TAB_NAME, VENDOR_COLUMNS],
    [CHART_OF_ACCOUNT_TAB_NAME, CHART_OF_ACCOUNT_COLUMNS],
    [PRODUCT_TAB_NAME, PRODUCT_COLUMNS],
    [COMPANY_BANK_ACCOUNT_TAB_NAME, COMPANY_BANK_ACCOUNT_COLUMNS],
    [USER_TAB_NAME, USER_COLUMNS],
    [PURCHASE_ORDER_TAB_NAME, PURCHASE_ORDER_COLUMNS],
    [PO_ITEM_TAB_NAME, PO_ITEM_COLUMNS],
    [GOODS_RECEIPT_TAB_NAME, GOODS_RECEIPT_COLUMNS],
    [GOODS_RECEIPT_ITEM_TAB_NAME, GOODS_RECEIPT_ITEM_COLUMNS],
    [ACCOUNTS_PAYABLE_TAB_NAME, ACCOUNTS_PAYABLE_COLUMNS],
    [PAYMENT_PREP_TAB_NAME, PAYMENT_PREP_COLUMNS],
    [PAYMENT_PREP_ITEM_TAB_NAME, PAYMENT_PREP_ITEM_COLUMNS],
    [PAYMENT_TAB_NAME, PAYMENT_COLUMNS],
  ] as const) {
    await ensureTab(tabName, columns);
    console.log(`สร้าง/อัปเดตแถวหัวตารางของ tab "${tabName}" เรียบร้อย`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
